name: gcloud-deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v2

      - id: deploy-contact
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: contact
          runtime: python38
          region: europe-west1
          credentials: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          env_vars: HUBSPOT_API_KEY=${{ secrets.HUBSPOT_API_KEY }},ACCESS_CONTROL_ALLOW_ORIGIN=${{ secrets.ACCESS_CONTROL_ALLOW_ORIGIN }},SUPPORT_PIPELINE_TICKET_OWNER_ID=${{ secrets.SUPPORT_PIPELINE_TICKET_OWNER_ID }}
          source_dir: gcloud/functions/hubspot

      - id: deploy-subscribe
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: subscribe
          runtime: python38
          region: europe-west1
          credentials: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          env_vars: HUBSPOT_API_KEY=${{ secrets.HUBSPOT_API_KEY }},ACCESS_CONTROL_ALLOW_ORIGIN=${{ secrets.ACCESS_CONTROL_ALLOW_ORIGIN }}
          source_dir: gcloud/functions/hubspot
