name: semantic

on:
  pull_request:
    branches:
      - main

jobs:
  check-semantic-version:
    if: "!contains(github.event.head_commit.message, 'skipci')"
    uses: octue/workflows/.github/workflows/check-semantic-version.yml@main
    with:
      path: setup.py
      breaking_change_indicated_by: minor
